import { wedding } from "./types";

export const emptyWeddingContent: wedding = {
  _id: "",
  path: "",
  isActive: false,
  category: "",
  createdAt: new Date(0),
  groom: {
    shortName: "",
    fullName: "",
    fullNameWithTitle: "",
    fatherName: "",
    motherName: "",
    orderInFamily: "",
    instagram: "",
    bank: "",
    noRek: "",
  },
  bride: {
    shortName: "",
    fullName: "",
    fullNameWithTitle: "",
    fatherName: "",
    motherName: "",
    orderInFamily: "",
    instagram: "",
    bank: "",
    noRek: "",
  },
  quotes: {
    quote1: "",
    quote1From: "",
    quote2: "",
    quote2From: "",
  },
  akad: {
    time: "",
    date: "",
    place: "",
    liveLink: "",
  },
  resepsi: {
    time: "",
    date: "",
    place: "",
    mapsLink: "",
  },
  loveStory: {
    loveStoryActived: false,
    firstMeet: "",
    theProposal: "",
    marriage: "",
  },
  imageUrl: {
    groomImg: "",
    brideImg: "",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
  },
};
