import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jasa Pembuatan Website Undanga Pernikahan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth focus:scroll-auto">
      <body className={`antialiased`} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
